### ISSUE TITLE
代码中使用了APPKEY MS常量 代码示例却没有说明，导致接口报错404

### ISSUE THREAD

**Issue by liewkaitsan** [GetuiLaboratory/getui-pushapi-php-client-v2#2]
GtClient->auth()  鉴权时使用了APPKEY 和MS 两个不存的常量。导致鉴权失败所有接口访问都是404 。
测试用例中define了APPKEY 和MS 常量，所以不会报错， 但是readme中的代码示例没有提及。在排查时浪费很多时间。希望能修改下。
另外实例化client时`$api = new GtClient("消息推送服务地址","APPKEY", "APPID","MASTERSECRET");`  看勒源码之后发现只需要填写域名，很容易产生歧义。导致我一开始时多加了/v2

**Comment by smartboat** [comment]
感谢提出的建议，确实存在你说的情况，我们尽快完善相关代码和提示。

**Comment by humengcn** [comment]
由于 @liewkaitsan 所描述的 bug，导致这份 SDK 根本不能使用，麻烦尽快修改 @smartboat

**Comment by humengcn** [comment]
@GetuiLab  这个 PR 可以

**Comment by smartboat** [comment]
> @GetuiLab 这个 [PR](https://github.com/GetuiLaboratory/getui-pushapi-php-client-v2/pull/5) 可以合并了

**Comment by smartboat** [comment]
[5#issue](https://github.com/GetuiLaboratory/getui-pushapi-php-client-v2/pull/5#issue-559753078)
#已经解决
